checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - tests/*

build:
  environment:
    php:
      pecl_extensions:
        - msgpack
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=coverage.clover'
        coverage:
          file: 'coverage.clover'
          format: 'clover'

  nodes:
    php72:
      environment:
        php: 7.2
    php73:
      environment:
        php: 7.3
    php74:
      environment:
        php: 7.4
